import { ScrollView, Image, Text } from 'react-native';
import logo_image from '../assets/adaptive-icon.png';

export default function ScrollView_4() {
    return (
        <ScrollView>
            <Image source={logo_image} style={{width: 300, height: 300}}/>
            <Text>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat obcaecati sint aspernatur consequuntur quia sed laboriosam harum dolore, autem totam numquam quos tempora minima cumque ab! Blanditiis aperiam beatae ex, eveniet aliquid eligendi sit provident reiciendis delectus inventore labore impedit neque fugit accusantium numquam commodi fugiat quos et quo repellendus temporibus sunt tempore. Mollitia quasi laboriosam qui voluptatum, deleniti quo officia? Tempora dolore quo impedit nesciunt reiciendis nihil laboriosam adipisci, aut explicabo vero eaque temporibus quibusdam ad, eligendi architecto vel dicta deleniti fuga dolorem, voluptatum quod. Provident error sunt soluta, nobis aut velit! Fuga dolorem saepe esse illo illum, dicta adipisci magnam, omnis officia beatae mollitia quibusdam doloremque numquam voluptatem quas est quo nam. Veniam et voluptatibus tenetur consequatur aperiam voluptas in similique corrupti, tempora rerum repellendus? Adipisci, consequuntur magnam. Libero molestias ut labore quo, nihil beatae ipsum esse nostrum delectus est a sequi corporis hic consequatur qui culpa voluptates sint laudantium necessitatibus? Excepturi veritatis nisi tempora exercitationem beatae consectetur molestias? Minima officia deserunt ratione iure natus aliquam, est fuga odit dolore quaerat maxime doloremque cupiditate earum expedita hic repellendus neque optio incidunt? Itaque quisquam assumenda dolor, repellendus autem sed recusandae eaque maxime consequuntur! At tempora quo hic accusantium quaerat voluptatum odit dolor necessitatibus eligendi quam sequi deserunt architecto dolorem, quia officia velit assumenda labore sapiente unde id tenetur earum. Perferendis blanditiis molestias ipsum reprehenderit repudiandae vero, voluptatem eveniet voluptatum quasi voluptas. Officiis quia error inventore autem, reiciendis at in nulla, saepe labore culpa mollitia atque nam, quod dignissimos expedita vitae aspernatur? Veniam aliquam culpa quis nobis iusto accusantium impedit explicabo, vitae molestias modi inventore eligendi. Iure est minima repellat consequuntur iste dicta repudiandae dolorum neque fuga pariatur ipsam veniam enim alias voluptas cumque, obcaecati aliquid, voluptate beatae! Pariatur excepturi laudantium reiciendis nisi animi consequatur eum voluptas ratione alias vero!
            </Text>
        </ScrollView>
    )
}